FROM ngnix 
RUN rm -rf /usr/share/nginx/html/index.html
RUN rm -rf /etc/nginx/conf.nginx
RUN rm -rf /etc/nginx/conf.nginx/default.conf
COPY expense.conf/etc/nginx/nginx.conf
COPY code  /usr/share/nginx/html/